package com.forkdevs.driveos.platform.iot.domain.model.aggregates;

import com.forkdevs.driveos.platform.iot.domain.model.valueobjects.DtcAlertId;
import com.forkdevs.driveos.platform.iot.domain.model.valueobjects.DtcAlertSeverity;
import com.forkdevs.driveos.platform.shared.domain.model.aggregates.AbstractDomainAggregateRoot;
import com.forkdevs.driveos.platform.shared.domain.model.valueobjects.BranchId;
import lombok.Getter;

import java.time.Instant;
import java.util.UUID;

/**
 * Domain Aggregate Root representing a DTC Alert generated by a vehicle.
 */
@Getter
public class DtcAlert extends AbstractDomainAggregateRoot<DtcAlert> {

    private DtcAlertId id;
    private UUID telemetrySnapshotId;
    private BranchId branchId;
    private String dtcCode;
    private String description;
    private DtcAlertSeverity severity;
    private Instant createdAt;

    public DtcAlert() {
    }

    public DtcAlert(
            DtcAlertId id,
            UUID telemetrySnapshotId,
            BranchId branchId,
            String dtcCode,
            String description,
            DtcAlertSeverity severity,
            Instant createdAt
    ) {
        this.id = id;
        this.telemetrySnapshotId = telemetrySnapshotId;
        this.branchId = branchId;
        this.dtcCode = dtcCode;
        this.description = description;
        this.severity = severity;
        this.createdAt = createdAt != null ? createdAt : Instant.now();
    }
}
