package com.smartfinance.smartfinancedriveplatform.iam.application.outboundservices;

import com.smartfinance.smartfinancedriveplatform.iam.domain.model.valueobjects.FirebasePhoneClaims;

/**
 * Outbound port for cryptographic validation of Firebase ID Tokens.
 */
public interface FirebaseTokenVerifierService {

    /**
     * Verifies the integrity, signature, and claims of the provided Firebase ID Token.
     *
     * @param firebaseIdToken The raw JWT ID Token generated by Firebase Auth on the client.
     * @return The extracted verified claims including UID and verified phone number.
     */
    FirebasePhoneClaims verifyToken(String firebaseIdToken);
}
