package com.forkdevs.driveos.platform.billing.infrastructure.persistence.jpa.adapters;

import com.forkdevs.driveos.platform.billing.domain.model.aggregates.Voucher;
import com.forkdevs.driveos.platform.billing.domain.repositories.VoucherRepository;
import com.forkdevs.driveos.platform.billing.infrastructure.persistence.jpa.assemblers.VoucherPersistenceAssembler;
import com.forkdevs.driveos.platform.billing.infrastructure.persistence.jpa.entities.VoucherPersistenceEntity;
import com.forkdevs.driveos.platform.billing.infrastructure.persistence.jpa.repositories.VoucherJpaRepository;
import org.springframework.stereotype.Component;

import java.util.Optional;
import java.util.UUID;
import java.util.List;
import com.forkdevs.driveos.platform.shared.domain.model.valueobjects.BranchId;
import org.springframework.context.ApplicationEventPublisher;

/**
 * Implementation of the VoucherRepository domain interface using Spring Data JPA.
 * Responsible for saving the Voucher aggregate, mapping it to JPA entities, 
 * and dispatching any pending domain events generated by the aggregate (like VoucherPaidEvent).
 */
@Component
public class VoucherRepositoryImpl implements VoucherRepository {

    private final VoucherJpaRepository persistenceRepository;
    private final ApplicationEventPublisher eventPublisher;

    public VoucherRepositoryImpl(VoucherJpaRepository persistenceRepository, ApplicationEventPublisher eventPublisher) {
        this.persistenceRepository = persistenceRepository;
        this.eventPublisher = eventPublisher;
    }

    @Override
    public Voucher save(Voucher voucher) {
        boolean exists = voucher.getId() != null && persistenceRepository.existsById(voucher.getId());
        
        VoucherPersistenceEntity entity;
        if (exists) {
            entity = persistenceRepository.findById(voucher.getId()).orElseThrow();
        } else {
            entity = new VoucherPersistenceEntity();
        }
        
        VoucherPersistenceAssembler.updateEntityFromAggregate(entity, voucher);
        
        var savedEntity = persistenceRepository.save(entity);
        
        // Publish any domain events registered in the aggregate
        voucher.domainEvents().forEach(eventPublisher::publishEvent);
        voucher.clearDomainEvents();
        
        return VoucherPersistenceAssembler.toAggregate(savedEntity);
    }

    @Override
    public Optional<Voucher> findById(UUID id) {
        return persistenceRepository.findById(id)
                .map(VoucherPersistenceAssembler::toAggregate);
    }

    @Override
    public List<Voucher> findByBranchId(BranchId branchId) {
        return persistenceRepository.findByBranchId(branchId)
                .stream()
                .map(VoucherPersistenceAssembler::toAggregate)
                .toList();
    }
}
