package com.forkdevs.driveos.platform.billing.domain.repositories;

import com.forkdevs.driveos.platform.billing.domain.model.aggregates.Voucher;

import java.util.Optional;
import java.util.UUID;
import java.util.List;
import com.forkdevs.driveos.platform.shared.domain.model.valueobjects.BranchId;

/**
 * Repository interface for managing the persistence of {@link Voucher} aggregates.
 * Abstracts the underlying database technology (e.g., JPA, MongoDB).
 */
public interface VoucherRepository {
    /**
     * Saves a voucher to the database. If it's new, it creates it. If it exists, it updates it.
     * Also responsible for dispatching any pending domain events attached to the aggregate.
     * 
     * @param voucher the voucher aggregate to save
     * @return the saved voucher
     */
    Voucher save(Voucher voucher);
    /**
     * Retrieves a voucher by its unique identifier.
     * 
     * @param id the UUID of the voucher
     * @return an Optional containing the voucher if found, or empty otherwise
     */
    Optional<Voucher> findById(UUID id);
    /**
     * Retrieves all vouchers generated by a specific branch.
     * 
     * @param branchId the identifier of the branch
     * @return a list of vouchers
     */
    List<Voucher> findByBranchId(BranchId branchId);
}
